# This is a basic workflow to help you get started with Actions

name: Build & Test

# Controls when the action will run.
on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

# added using https://github.com/step-security/secure-repo
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bmake cmake

      - name: Build with GNU Make
        run: make clean all

      - name: Test with GNU Make
        run: make test

      - name: Build with BSD Make
        run: bmake clean all

      - name: Test with BSD Make
        run: bmake test

      - name: Build with CMake
        run: |
          cmake -B build
          make -C build clean all

      - name: Test with CMake
        run: bmake -C build test
