version: '3.6'

services:
  costumery:
    image: localhost/cyberquest_2023/ctf-costumery:latest
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - CHALLENGE_PORT=25565
      - FLAG=cq23{e45y_p34zy_l3m0n_squ33zy_455857558d7d1499aa7498949546a2b2}
    ulimits:
      nproc: 700